develop - test gitactions 2

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -1,49 +1,144 @@
-# Nom de notre workflow
-name: "Build and deploy Github pages"
+# # Nom de notre workflow
+# name: "Build and deploy Github pages"
 
-# Événements sur lesquels il doit être déclenché
+# # Événements sur lesquels il doit être déclenché
+# on:
+#   push:         # <- Déclenché lorsque l'on pousse du code...
+#     branches:
+#       - develop  # <- ... mais seulement sur la branche "master"
+
+# jobs:
+
+#   # Notre job
+#   build-and-deploy:
+#     runs-on: ubuntu-latest
+
+#     # Tâches à effectuer, comme expliquées ci-dessus
+#     steps:
+
+#       # 1. On récupère le contenu du dépôt
+
+#       - name: "Checkout"
+#         uses: actions/checkout@v2
+#         with:
+#           persist-credentials: false
+#       - uses: actions/setup-node@v1
+#         with:
+#           node-version: 12
+#       - run: yarn install
+#       - run: yarn next build # Runs next build
+#       - run: yarn next export # Runs next export and generates the out directory
+#       - run: touch out/.nojekyll
+
+#       # - name: "Install Python dependencies"
+#       #   run: |
+#       #     pip3 install setuptools
+#       #     pip3 install sphinx sphinx-rtd-theme
+
+#       # - name: "Build Sphinx Doc"
+#       #   run: |
+#       #     make html
+
+#       # 3. Déploiement sur les Github Pages
+
+#       - name: "Deploy Github Pages"
+#         uses: JamesIves/github-pages-deploy-action@3.7.1
+#         with:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#           BRANCH: gh-pages     # <- Branche sur laquelle seront commités les fichiers
+#           FOLDER: ./out  # <- Dossier contenant notre documentation générée
+
+# Sample workflow for building and deploying a Next.js site to GitHub Pages
+#
+# To get started with Next.js see: https://nextjs.org/docs/getting-started
+#
+name: Deploy Next.js site to Pages
+
 on:
-  push:         # <- Déclenché lorsque l'on pousse du code...
-    branches:
-      - develop  # <- ... mais seulement sur la branche "master"
+  # Runs on pushes targeting the default branch
+  push:
+    branches: ["feature/github-pages-actions"]
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow one concurrent deployment
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
 
 jobs:
-
-  # Notre job
-  build-and-deploy:
+  # Build job
+  build:
     runs-on: ubuntu-latest
-
-    # Tâches à effectuer, comme expliquées ci-dessus
     steps:
-
-      # 1. On récupère le contenu du dépôt
-
-      - name: "Checkout"
-        uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
         with:
-          persist-credentials: false
-      - uses: actions/setup-node@v1
+          node-version: "16"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v2
         with:
-          node-version: 12
-      - run: yarn install
-      - run: yarn next build # Runs next build
-      - run: yarn next export # Runs next export and generates the out directory
-      - run: touch out/.nojekyll
-
-      # - name: "Install Python dependencies"
-      #   run: |
-      #     pip3 install setuptools
-      #     pip3 install sphinx sphinx-rtd-theme
-
-      # - name: "Build Sphinx Doc"
-      #   run: |
-      #     make html
-
-      # 3. Déploiement sur les Github Pages
-
-      - name: "Deploy Github Pages"
-        uses: JamesIves/github-pages-deploy-action@3.7.1
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: next
+      - name: Restore cache
+        uses: actions/cache@v3
         with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          BRANCH: gh-pages     # <- Branche sur laquelle seront commités les fichiers
-          FOLDER: ./out  # <- Dossier contenant notre documentation générée
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Static HTML export with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} next export
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./out
+
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
